############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Events"
url = "event/"
weight = 2

[[main]]
name = "Team"
url = "authors/"
weight = 3

[[main]]
name = "Sessions"
url = "sessions/"
weight = 4

# footer menu
[[footer]]
name = "Anmeldung Workplace Ninja Summit 2024 in Luzern"
url = "https://www.wpninjas.ch/"
weight = 1
